port: ${PORT}
auth:
  secret: ${AUTH_SECRET}
  duration: 15
twilio:
  sid: ${TWILIO_SID}
  token: ${TWILIO_TOKEN}
  verify: ${TWILIO_VERIFY}
stripe:
  key: ${STRIPE_KEY}
storage:
  bucketName: finchat-storage
mysql:
  connectionString: ${MYSQL_CONN_STR}
