port: ${PORT}
logger: true
errorReporting: false
webhookToken: ${WEBHOOK_TOKEN}
twilio:
  sid: ${TWILIO_SID}
  token: ${TWILIO_TOKEN}
  verify: ${TWILIO_VERIFY}
stripe:
  key: ${STRIPE_KEY}
pubnub:
  pubKey: ${PUB_KEY}
  subKey: ${SUB_KEY}
  secKey: ${SEC_KEY}
  serverUUID: ${SERVER_UUID}
storage:
  bucketName: finchat-storage
mysql:
  connectionString: ${MYSQL_CONN_STR}
