name: e2e tests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_DATABASE: core
        ports:
          - 3306:3306

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: "1.16"

      - name: Check if builds
        run: |
          go build ./...

      - name: Run e2e tests
        env:
          MYSQL_CONN_STR: "root:@tcp(localhost:3306)/core?parseTime=true"
        run: |
          go test -v ./...
